### ISSUE TITLE
setInterval() ?

### ISSUE THREAD

**Issue by lavara123** [enimax-anime/key-extractor#3]
The setInterval() inside the eval js code that the key-extractor returns is unnecessary and unsafe in my opinion.

ID = 6

**Comment by enimax-anime** [comment]
It is unnecessary indeed, but they change their JS file a lot, so it is difficult to avoid. Also, since it is eval'ed in a sandboxed iframe on the android app, it shouldn't be an issue.

**Comment by enimax-anime** [comment]
Also, `eval.html` is refreshed after the code has been evaluated, so setInterval shouldn't cause any performance issue either.
